apiVersion: v1
kind: Service
metadata:
  namespace: elk-stack
  name: dom-afiliacion-service
  labels:
    app: dom-afiliacion-service
spec:
  selector:
    app: dom-afiliacion-service
  ports:
    - name: dom-afiliacion-service
      port: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dom-afiliacion-service
  namespace: elk-stack
  labels:
    app: dom-afiliacion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dom-afiliacion-service
  template:
    metadata:
      labels:
        app: dom-afiliacion-service
        role: rolling-update
    spec:
      containers:
      - name: dom-afiliacion-container
        image: 142103498481.dkr.ecr.us-west-2.amazonaws.com/eks/dom-afiliacion-service:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    # rollingUp      maxSurge: 50%